version: "3.7"
services: 
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG_ELK}
    restart: unless-stopped
    env_file: .env
    environment: 
      - network.host=0.0.0.0
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
    ports: 
      - "9200:9200"
      - "9300:9300"
  
  kibana:
    image: docker.elastic.co/kibana/kibana:${TAG_ELK}
    restart: unless-stopped
    env_file: .env
    environment: 
      - ELASTICSEARCH_HOSTS=http://${IP_ELASTICSEARCH}:9200
      # - XPACK_GRAPH_ENABLED=true
      # - XPACK_WATCHER_ENABLED=true
      # - XPACK_ML_ENABLED=true
      - MONITORING_ENABLED=true
      - xpack.monitoring.ui.container.elasticsearch.enabled=true
    ports: 
      - "5601:5601"
    depends_on: 
      - elasticsearch
  
  logstash:
    image: docker.elastic.co/logstash/logstash:${TAG_ELK}
    restart: unless-stopped
    env_file: .env
    environment: 
      - http.host=0.0.0.0
      - xpack.monitoring.elasticsearch.hosts=http://${IP_ELASTICSEARCH}:9200
      - XPACK_MONITORING_ENABLED=true
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
    ports:
      - "5044:5044"
      - "9600:9600"
    depends_on: 
      - elasticsearch
